@startuml Artefact 
!theme plain


interface ActionNumberArtefactFactory{
    + createActionNumberArtefact()
}

interface HealthArtefactFactory{
    + createActionNumberArtefact()
}

interface MovementArtefactFactory{ 
    + createMovementArtefact()
}

interface WeaponArtefactFactory{ 
    + createChangeWeaponArtefact()
}

abstract Artefact {
    + abstract execute(subject : ArtefactUser)
}

abstract Artefact implements GameObject 
Artefact .R.> ArtefactUser

ActionNumberArtefactFactory .U.> Artefact
HealthArtefactFactory .R.> Artefact
MovementArtefactFactory .U.> Artefact
WeaponArtefactFactory .U.> Artefact


@enduml 